.Dd $Mdocdate: August 18 2013 $
.Dt COOKIECUTTER 1
.Os
.Sh NAME
.Nm cookiecutter
.Nd create projects from project templates
.Sh SYNOPSIS
.Nm
.Op Fl h
.Ar input
.Sh DESCRIPTION
.Nm
is a command-line tool to create projects from project templates. It
takes as input a template which is either a local directory or an URL
to a repository.
.Nm
will then generate the project from the template. It may ask questions
to fill in some values.
.Sh SEE ALSO
For more documentation about
.Nm ,
have a look at
.Pa /usr/share/doc/python-cookiecutter-doc/html/index.html .
